In [1]:
import pandas as pd 
import numpy as np

import sys
import os
EDHREC_REPO_PATH = '..'
sys.path.append(os.path.abspath(EDHREC_REPO_PATH))
# Set the environment variables
os.environ['APP_ENVIRONMENT'] = 'dev'
os.environ['APP_NAME'] = 'api'
os.environ['AWS_DEFAULT_REGION'] = 'us-east-2'
os.environ['APP_CONFIG_DIR'] = os.path.abspath(f'{EDHREC_REPO_PATH}/edhrec/configs/')

from edhrec.plus.query import athena
from edhrec.plus.jobs.count_warehouse.config import (
    ATHENA_WORKGROUP,
    ICEBERG_WAREHOUSE,
)

import plotly.express as px
import logging

# Add this at the top of your notebook/script
logging.getLogger('PIL').setLevel(logging.WARNING)

### Querying from Iceberg to get "depth" data

In [2]:
#engine = athena.AthenaQueryEngine(athena_workgroup = ATHENA_WORKGROUP, iceberg_warehouse = ICEBERG_WAREHOUSE)

# ending_columns = ['commander', 'commander2', 'color', 'earliest_sets', 'released_at', 'user_id', 'first_create_time', 'first_update_date', 'last_update_date', 'total_active_time', 'num_updates']

# query_str = f"""

# WITH date_span AS (
#     SELECT MIN(update_time) as min_update_time, MAX(update_time) as max_update_time
#     FROM prod.all_decks
#     WHERE user_id IS NOT NULL and create_time IS NOT NULL
# ),

# deck_history AS (
#     SELECT commander_id, commander2_id, deck_color_id, user_id, create_time, DATE(update_time) as update_date
#     FROM prod.all_decks
#     WHERE user_id IS NOT NULL and update_time >= create_time + INTERVAL '60' DAY
# ),

# -- limit to only one update per commander/user/day to avoid overcounting updates for users who make multiple updates in a day
# deck_history_daily_updates AS (
#     SELECT commander_id, commander2_id, deck_color_id, user_id, update_date, MIN(create_time) as create_time, 1 as num_updates
#     FROM deck_history
#     GROUP BY commander_id, commander2_id, deck_color_id, user_id, update_date
# ),

# -- get total number of updates by user and commander
# user_commander_update_counts AS (
#     SELECT commander_id, commander2_id, user_id, 
#         MIN(create_time) as first_create_time,
#         MIN(update_date) as first_update_date,
#         MAX(update_date) as last_update_date,
#         DATE_DIFF('day', MIN(create_time), MAX(update_date)) as total_active_time,
#         SUM(num_updates) as num_updates
#     FROM deck_history_daily_updates
#     GROUP BY commander_id, commander2_id, user_id
# ),

# commander_list AS (
#     SELECT DISTINCT commander_id, commander2_id, deck_color_id
#     FROM deck_history
# ), 

# commander_info AS (
#     SELECT commander_id, commander2_id, 
#         cr1.name as commander, cr2.name as commander2,
#         GREATEST(cr1.released_at, COALESCE(cr2.released_at, cr1.released_at)) as released_at,
#         CASE WHEN cr2.earliest_set IS NULL 
#             THEN ARRAY[cr1.earliest_set]
#             ELSE ARRAY[cr1.earliest_set, cr2.earliest_set]
#             END as earliest_sets,
#         cc.alphabetical_combination as color
#     FROM commander_list
#     JOIN prod.card_ref cr1 ON commander_list.commander_id = cr1.card_id
#     LEFT JOIN prod.card_ref cr2 ON commander_list.commander2_id = cr2.card_id
#     JOIN prod.color_combinations cc ON commander_list.deck_color_id = cc.value
# )

# SELECT {', '.join(ending_columns)}
# FROM user_commander_update_counts ucuc
# JOIN commander_info ci
#     ON ucuc.commander_id = ci.commander_id
#     AND ucuc.commander2_id IS NOT DISTINCT FROM ci.commander2_id
# ORDER BY commander, commander2, user_id
# """

# raw_results = engine.execute(query_str)

# df = pd.DataFrame(raw_results, columns=ending_columns)

# df

In [9]:
df = pd.read_csv("depth_vs_breadth_raw_data.csv")
df['released_at'] = pd.to_datetime(df['released_at'])

df['time_since_release'] = (pd.to_datetime('today') - pd.to_datetime(df['released_at'])).dt.days
df['time_since_release'] = np.where(df['time_since_release'] >= 365*2, 365*2, df['time_since_release'])

# convert from string representation of list back to list
df['earliest_sets'] = df['earliest_sets'].apply(lambda x: tuple(eval(x)) if isinstance(x, str) else x)

df

/var/folders/_k/kyjp44cj6493znjb_xjbld0r0000gn/T/ipykernel_42880/1385567191.py:1: DtypeWarning: Columns (0: commander2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("depth_vs_breadth_raw_data.csv")

,commander,commander2,color,earliest_sets,released_at,user_id,first_create_time,first_update_date,last_update_date,total_active_time,num_updates,time_since_release
0,"""Brims"" Barone, Midway Mobster",NaN,BW,"(unf,)",2022-10-07,156055,2023-04-29 15:06:53+00:00,2025-12-14,2025-12-14,959,1,730
1,"""Brims"" Barone, Midway Mobster",NaN,BW,"(unf,)",2022-10-07,19915,2023-11-19 00:00:00+00:00,2024-03-24,2024-03-24,126,1,730
2,"""Brims"" Barone, Midway Mobster",NaN,BW,"(unf,)",2022-10-07,201498,2025-10-08 06:49:08+00:00,2025-12-22,2025-12-26,78,2,730
3,"""Brims"" Barone, Midway Mobster",NaN,BW,"(unf,)",2022-10-07,236905,2024-09-18 00:00:00+00:00,2024-12-23,2024-12-23,96,1,730
4,"""Brims"" Barone, Midway Mobster",NaN,BW,"(unf,)",2022-10-07,35613,2025-03-15 00:00:00+00:00,2025-06-05,2025-06-05,82,1,730
...,...,...,...,...,...,...,...,...,...,...,...,...
2662348,"Éowyn, Shieldmaiden",NaN,RUW,"(ltc,)",2023-06-23,zootfarm,2024-12-01 00:00:00+00:00,2025-05-09,2025-11-22,356,5,730
2662349,"Éowyn, Shieldmaiden",NaN,RUW,"(ltc,)",2023-06-23,zozpreston,2023-08-25 16:25:52.807000+00:00,2023-10-28,2023-10-28,63,1,730
2662350,"Éowyn, Shieldmaiden",NaN,RUW,"(ltc,)",2023-06-23,zulla24,2025-01-27 00:00:00+00:00,2025-07-08,2026-01-25,363,3,730
2662351,"Éowyn, Shieldmaiden",NaN,RUW,"(ltc,)",2023-06-23,zunigarillo,2025-10-25 05:09:30.287000+00:00,2025-12-31,2026-04-06,162,7,730
2662352,"Éowyn, Shieldmaiden",NaN,RUW,"(ltc,)",2023-06-23,zwika47,2024-09-30 00:00:00+00:00,2025-03-04,2025-09-18,353,3,730

In [10]:
df['commanders'] = df.apply(lambda row: f"{row['commander']} + {row['commander2']}" if pd.notna(row['commander2']) else row['commander'], axis=1)

keep_commanders = df.groupby('commanders')['user_id'].nunique().reset_index()\
    .rename(columns={"user_id": "num_users"})\
    .query("num_users > 200")\
    ['commanders'].values.tolist()

keep_commanders

['Aang, at the Crossroads',
 'Aatchik, Emerald Radian',
 'Abaddon the Despoiler',
 "Abdel Adrian, Gorion's Ward + Candlekeep Sage",
 "Abdel Adrian, Gorion's Ward + Far Traveler",
 'Abigale, Eloquent First-Year',
 'Abomination of Llanowar',
 'Absolute Virtue',
 'Abuelo, Ancestral Echo',
 'Acererak the Archlich',
 'Aclazotz, Deepest Betrayal',
 'Adeline, Resplendent Cathar',
 'Adeliz, the Cinder Wind',
 'Admiral Beckett Brass',
 'Admiral Brass, Unsinkable',
 'Adrix and Nev, Twincasters',
 'Aegar, the Freezing Flame',
 'Aerith Gainsborough',
 'Aerith, Last Ancient',
 'Aesi, Tyrant of Gyre Strait',
 'Aeve, Progenitor Ooze',
 'Agatha of the Vile Cauldron',
 'Agent Frank Horrigan',
 'Agrus Kos, Eternal Soldier',
 'Aisha of Sparks and Smoke',
 'Ajani, Nacatl Pariah',
 'Akiri, Fearless Voyager',
 'Akiri, Line-Slinger + Ardenn, Intrepid Archaeologist',
 'Akiri, Line-Slinger + Silas Renn, Seeker Adept',
 'Akiri, Line-Slinger + Thrasios, Triton Hero',
 'Akroma, Vision of Ixidor + Rograkh, Son of Rohgahh',
 'Akul the Unrepentant',
 'Alandra, Sky Dreamer',
 'Alania, Divergent Storm',
 'Alaundo the Seer',
 'Alela, Artful Provocateur',
 'Alela, Cunning Conqueror',
 'Alena, Kessig Trapper + Gilanra, Caller of Wirewood',
 'Alesha, Who Laughs at Fate',
 'Alesha, Who Smiles at Death',
 'Alexios, Deimos of Kosmos',
 'Alibou, Ancient Witness',
 'Alisaie Leveilleur + Alphinaud Leveilleur',
 'Alistair, the Brigadier',
 'Aloy, Savior of Meridian',
 'Alquist Proft, Master Sleuth',
 "Altaïr Ibn-La'Ahad",
 'Amalia Benavides Aguirre',
 'Amareth, the Lustrous',
 'Aminatou, Veil Piercer',
 'Aminatou, the Fateshifter',
 'Amy Rose',
 "Amzu, Swarm's Hunger",
 'Anafenza, the Foremost',
 'Angus Mackenzie',
 'Anhelo, the Painter',
 'Anikthea, Hand of Erebos',
 'Anim Pakal, Thousandth Moon',
 'Animar, Soul of Elements',
 'Anje Falkenrath',
 'Anje, Maid of Dishonor',
 'Annie Flash, the Veteran',
 'Anowon, the Ruin Thief',
 'Anrakyr the Traveller',
 'Anti-Venom, Horrifying Healer',
 'Anzrag, the Quake-Mole',
 'Ao, the Dawn Sky',
 'Aphelia, Viper Whisperer',
 'Apothecary White',
 'Appa, Steadfast Guardian',
 'Arabella, Abandoned Doll',
 'Aragorn and Arwen, Wed',
 'Aragorn, Hornburg Hero',
 'Aragorn, King of Gondor',
 'Aragorn, the Uniter',
 'Arahbo, Roar of the World',
 'Arahbo, the First Fang',
 'Araumi of the Dead Tide',
 'Arbaaz Mir',
 'Arcades, the Strategist',
 'Arcanis the Omnipotent',
 'Archangel Avacyn',
 'Archelos, Lagoon Mystic',
 'Arcum Dagsson',
 'Ardbert, Warrior of Darkness',
 'Ardenn, Intrepid Archaeologist + Esior, Wardwing Familiar',
 'Ardenn, Intrepid Archaeologist + Kediss, Emberclaw Familiar',
 "Ardenn, Intrepid Archaeologist + Kraum, Ludevic's Opus",
 'Ardenn, Intrepid Archaeologist + Rograkh, Son of Rohgahh',
 'Ardenn, Intrepid Archaeologist + Tana, the Bloodsower',
 'Ardyn, the Usurper',
 'Arixmethes, Slumbering Isle',
 'Arjun, the Shifting Flame',
 'Armix, Filigree Thrasher + Silas Renn, Seeker Adept',
 'Arna Kennerüd, Skycaptain',
 'Arthur, Marigold Knight',
 'Arvinox, the Mind Flail',
 'Arwen Undómiel',
 'Arwen, Mortal Queen',
 'Arwen, Weaver of Hope',
 'Aryel, Knight of Windgrace',
 'Ashad, the Lone Cyberman',
 'Ashaya, Soul of the Wild',
 'Ashcoat of the Shadow Swarm',
 'Ashling the Pilgrim',
 'Ashling, Flame Dancer',
 'Ashling, Rekindled',
 'Ashling, the Limitless',
 'Ashnod the Uncaring',
 'Ashnod, Flesh Mechanist',
 'Asmoranomardicadaistinaculdacar',
 'Astarion, the Decadent',
 'Astor, Bearer of Blades',
 'Atarka, World Render',
 'Atemsis, All-Seeing',
 'Athreos, God of Passage',
 'Athreos, Shroud-Veiled',
 'Atla Palani, Nest Tender',
 'Atogatog',
 'Atraxa, Grand Unifier',
 "Atraxa, Praetors' Voice",
 'Atreus, Impulsive Son + Kratos, Stoic Father',
 'Atris, Oracle of Half-Truths',
 'Auntie Blyte, Bad Influence',
 'Auntie Ool, Cursewretch',
 'Aurelia, Exemplar of Justice',
 'Aurelia, the Law Above',
 'Aurelia, the Warleader',
 'Avacyn, Angel of Hope',
 'Avatar Aang',
 'Avatar Roku, Firebender',
 'Aveline de Grandpré',
 'Averna, the Chaos Bloom',
 'Ayara, First of Locthwain',
 'Ayara, Widow of the Realm',
 'Ayesha Tanaka, Armorer',
 'Ayli, Eternal Pilgrim',
 'Ayula, Queen Among Bears',
 'Azami, Lady of Scrolls',
 'Azlask, the Swelling Scourge',
 'Azusa, Lost but Seeking',
 'Baba Lysaga, Night Witch',
 'Baeloth Barrityl, Entertainer + Clan Crafter',
 'Baeloth Barrityl, Entertainer + Noble Heritage',
 'Baeloth Barrityl, Entertainer + Raised by Giants',
 'Balan, Wandering Knight',
 'Baldin, Century Herdmaster',
 'Balmor, Battlemage Captain',
 'Balthier and Fran',
 'Balthor the Defiled',
 'Bane, Lord of Darkness',
 'Baral and Kari Zev',
 'Baral, Chief of Compliance',
 'Bartolomé del Presidio',
 'Baru, Wurmspeaker',
 'Basim Ibn Ishaq',
 'Baylen, the Haymaker',
 "Be'lakor, the Dark Master",
 'Belbe, Corrupted Observer',
 'Beledros Witherbloom',
 'Belisarius Cawl',
 'Bello, Bard of the Brambles',
 'Beluna Grandsquall',
 'Bess, Soul Nourisher',
 "Betor, Ancestor's Voice",
 'Betor, Kin to All',
 'Beza, the Bounding Spring',
 'Bhaal, Lord of Murder',
 'Bilbo, Birthday Celebrant',
 'Birgi, God of Storytelling',
 "Bjorna, Nightfall Alchemist + Wernog, Rider's Chaplain",
 'Black Cat, Cunning Thief',
 'Black Panther, Wakandan King',
 'Black Waltz No. 3',
 'Bladewing, Deathless Tyrant',
 'Blaster, Combat DJ',
 'Blex, Vexing Pest',
 'Blim, Comedic Genius',
 'Blind Seer',
 'Bohn, Beguiling Balladeer',
 'Bonny Pall, Clearcutter',
 'Borborygmos Enraged',
 'Borborygmos and Fblthp',
 'Bosh, Iron Golem',
 'Brago, King Eternal',
 'Braids, Arisen Nightmare',
 'Braids, Cabal Minion',
 'Braids, Conjurer Adept',
 'Brallin, Skyshark Rider + Shabraz, the Skyshark',
 'Bre of Clan Stoutarm',
 'Breeches, Brazen Plunderer + Malcolm, Keen-Eyed Navigator',
 'Breeches, the Blastmaker',
 'Breena, the Demagogue',
 'Brenard, Ginger Sculptor',
 'Breya, Etherium Shaper',
 'Bria, Riptide Rogue',
 'Bright-Palm, Soul Awakener',
 "Brigid, Clachan's Heart",
 'Brigone, Soldier of Meletis',
 'Brimaz, Blight of Oreskos',
 'Brion Stoutarm',
 'Bristly Bill, Spine Sower',
 'Brokkos, Apex of Forever',
 'Brudiclad, Telchor Engineer',
 'Bruenor Battlehammer',
 'Bruna, Light of Alabaster',
 'Bruna, the Fading Light',
 'Bruse Tarl, Boorish Herder + Ikra Shidiqi, the Usurper',
 'Bruse Tarl, Boorish Herder + Thrasios, Triton Hero',
 'Bruse Tarl, Roving Rancher',
 'Bruvac the Grandiloquent',
 'Bumi, Unleashed',
 'Burakos, Party Leader + Folk Hero',
 'Burakos, Party Leader + Guild Artisan',
 'Burakos, Party Leader + Haunted One',
 'Byrke, Long Ear of the Law',
 'Cadira, Caller of the Small',
 'Cadric, Soul Kindler',
 "Caesar, Legion's Emperor",
 'Cait, Cage Brawler',
 'Calamity, Galloping Inferno',
 'Calix, Guided by Fate',
 'Camellia, the Seedmiser',
 'Captain America, First Avenger',
 'Captain Howler, Sea Scourge',
 "Captain N'ghathrod",
 'Captain Rex Nebula',
 'Captain Sisay',
 'Captain Storm, Cosmium Raider',
 'Caradora, Heart of Alacria',
 'Carmen, Cruel Skymarcher',
 'Carth the Lion',
 'Casal, Lurkwood Pathfinder',
 'Cayth, Famed Mechanist',
 'Cazur, Ruthless Stalker + Ukkima, Stalking Shadow',
 'Cecil, Dark Knight',
 'Cecily, Haunted Mage + Elmar, Ulvenwald Informant',
 'Cecily, Haunted Mage + Othelm, Sigardian Outcast',
 'Cecily, Haunted Mage + Sophina, Spearsage Deserter',
 "Cecily, Haunted Mage + Wernog, Rider's Chaplain",
 'Celes, Rune Knight',
 'Celestine, the Living Saint',
 'Chainer, Dementia Master',
 'Chainer, Nightmare Adept',
 'Chandra, Fire of Kaladesh',
 'Charix, the Raging Isle',
 'Chatterfang, Squirrel General',
 'Chevill, Bane of Monsters',
 'Child of Alara',
 'Chishiro, the Shattered Blade',
 'Chiss-Goria, Forge Tyrant',
 'Choco, Seeker of Paradise',
 'Chromium, the Mutable',
 'Chulane, Teller of Tales',
 'Cid, Timeless Artificer',
 'Circu, Dimir Lobotomist',
 'Clavileño, First of the Blessed',
 'Clement, the Worrywort',
 'Cleopatra, Exiled Pharaoh',
 "Clive, Ifrit's Dominant",
 'Cloud, Ex-SOLDIER',
 'Cloud, Midgar Mercenary',
 "Cloud, Planet's Champion",
 'Codie, Vociferous Codex',
 'Colfenor, the Last Yew',
 'Commander Liara Portyr',
 'Commander Mustard',
 'Commissar Severina Raine',
 'Commodore Guff',
 'Coram, the Undertaker',
 'Cormela, Glamour Thief',
 'Cosima, God of the Voyage',
 'Cosmic Spider-Man',
 'Craig Boone, Novac Guard',
 'Cromat',
 'Crosis, the Purger',
 'Cult of Skaro',
 'Curie, Emergent Intelligence',
 'Cynette, Jelly Drover',
 'Círdan the Shipwright',
 'Dakkon Blackblade',
 'Dalakos, Crafter of Wonders',
 'Damia, Sage of Stone',
 'Daretti, Scrap Savant',
 'Dargo, the Shipwrecker + Jeska, Thrice Reborn',
 'Dargo, the Shipwrecker + Malcolm, Keen-Eyed Navigator',
 'Dargo, the Shipwrecker + Thrasios, Triton Hero',
 'Dargo, the Shipwrecker + Tymna the Weaver',
 'Darien, King of Kjeldor',
 'Davros, Dalek Creator',
 'Dawnsire, Sunstar Dreadnought',
 'Daxos of Meletis',
 'Daxos the Returned',
 'Daxos, Blessed by the Sun',
 'Deadpool, Trading Card',
 'Deathleaper, Terror Weapon',
 'Dee Kay, Finder of the Lost',
 'Delina, Wild Mage',
 'Delney, Streetwise Lookout',
 'Denry Klin, Editor in Chief',
 'Depala, Pilot Exemplar',
 'Derevi, Empyrial Tactician',
 'Dihada, Binder of Wills',
 'Dina, Soul Steeper',
 "Dion, Bahamut's Dominant",
 'Dionus, Elvish Archdruid',
 'Disa the Restless',
 'Djeru and Hazoret',
 'Doc Aurlock, Grizzled Genius',
 'Doctor Octopus, Master Planner',
 'Dogmeat, Ever Loyal',
 'Don Andres, the Renegade',
 'Donal, Herald of Wings',
 'Doran, Besieged by Time',
 'Doran, the Siege Tower',
 'Dr. Eggman',
 'Dr. Madison Li',
 'Drafna, Founder of Lat-Nam',
 "Dragonhawk, Fate's Tempest",
 'Dragonlord Ojutai',
 'Drana and Linvala',
 'Drivnod, Carnage Dominus',
 "Drizzt Do'Urden",
 'Duke Ulder Ravengard',
 'Durnan of the Yawning Portal + Passionate Archaeologist',
 'Duskana, the Rage Mother',
 'Dyadrine, Synthesis Amalgam',
 'Dynaheir, Invoker Adept',
 'Eddie Brock',
 'Edea, Possessed Sorceress',
 'Edgar Markov',
 'Edgar, Charmed Groom',
 'Edric, Spymaster of Trest',
 'Edward Kenway',
 'Eight-and-a-Half-Tails',
 'Eirdu, Carrier of Dawn',
 'Eivor, Battle-Ready',
 'Eivor, Wolf-Kissed',
 'Eladamri, Korvecdal',
 'Eladamri, Lord of Leaves',
 'Elas il-Kor, Sadistic Pilgrim',
 'Electro, Assaulting Battery',
 'Elenda and Azor',
 'Elenda, Saint of Dusk',
 'Elenda, the Dusk Rose',
 'Elesh Norn',
 'Elesh Norn, Grand Cenobite',
 'Elesh Norn, Mother of Machines',
 'Eligeth, Crossroads Augur + Kydele, Chosen of Kruphix',
 'Eligeth, Crossroads Augur + Siani, Eye of the Storm',
 'Ellie and Alan, Paleontologists',
 'Ellie, Brick Master + Joel, Resolute Survivor',
 'Ellie, Vengeful Hunter + Joel, Resolute Survivor',
 'Ellivere of the Wild Court',
 'Elmar, Ulvenwald Informant + Hargilde, Kindly Runechanter',
 "Elmar, Ulvenwald Informant + Wernog, Rider's Chaplain",
 'Elminster',
 'Eloise, Nephalia Sleuth',
 'Elrond of the White Council',
 'Elrond, Master of Healing',
 'Elsha of the Infinite',
 'Elsha, Threefold Master',
 'Eluge, the Shoreless Sea',
 'Emet-Selch of the Third Seat',
 'Emet-Selch, Unsundered',
 'Emiel the Blessed',
 'Emmara, Soul of the Accord',
 'Emperor Mihail II',
 'Empress Galina',
 'Emrakul, the Promised End',
 'Emry, Lurker of the Loch',
 'Endrek Sahr, Master Breeder',
 'Ephara, God of the Polis',
 'Erebos, God of the Dead',
 'Eriette of the Charmed Apple',
 'Eriette, the Beguiler',
 'Erinis, Gloom Stalker + Scion of Halaster',
 'Erinis, Gloom Stalker + Street Urchin',
 'Eris, Roar of the Storm',
 'Errant and Giada',
 'Ertai, the Corrupted',
 'Ertha Jo, Frontier Mentor',
 'Eruth, Tormented Prophet',
 'Eshki Dragonclaw',
 "Eshki, Temur's Roar",
 'Esika, God of the Tree',
 'Esior, Wardwing Familiar + Ishai, Ojutai Dragonspeaker',
 'Esix, Fractal Bloom',
 'Estrid, the Masked',
 'Etali, Primal Conqueror',
 'Etali, Primal Storm',
 'Etrata, Deadly Fugitive',
 'Etrata, the Silencer',
 'Eutropia the Twice-Favored',
 'Evelyn, the Covetous',
 'Evereth, Viceroy of Plunder',
 'Evra, Halcyon Witness',
 'Experiment Kraj',
 'Extus, Oriq Overlord',
 'Ezio Auditore da Firenze',
 'Ezrim, Agency Chief',
 'Ezuri, Claw of Progress',
 'Ezuri, Renegade Leader',
 'Ezuri, Stalker of Spheres',
 'Falco Spara, Pactweaver',
 'Faldorn, Dread Wolf Herald',
 'Fandaniel, Telophoroi Ascian',
 'Fangorn, Tree Shepherd',
 'Far Fortune, End Boss',
 'Faramir, Prince of Ithilien',
 'Farid, Enterprising Salvager',
 "Farideh, Devil's Chosen",
 'Fblthp, Lost on the Range',
 'Fblthp, the Lost',
 'Feather, Radiant Arbiter',
 'Feather, the Redeemed',
 'Feldon of the Third Path',
 'Felisa, Fang of Silverquill',
 'Felix Five-Boots',
 'Felothar the Steadfast',
 'Felothar, Dawn of the Abzan',
 'Finneas, Ace Archer',
 'Fire Lord Azula',
 'Fire Lord Zuko',
 'Firesong and Sunspeaker',
 'Firja, Judge of Valor',
 'Firkraag, Cunning Instigator',
 'Flamewar, Brash Veteran',
 'Florian, Voldaren Scion',
 'Flubs, the Fool',
 'Francisco, Fowl Marauder + Malcolm, Keen-Eyed Navigator',
 'Francisco, Fowl Marauder + Thrasios, Triton Hero',
 "Freyalise, Llanowar's Fury",
 'Frodo, Adventurous Hobbit + Sam, Loyal Attendant',
 "Frodo, Sauron's Bane",
 'Fumulus, the Infestation',
 'Fynn, the Fangbearer',
 "G'raha Tia, Scion Reborn",
 'Gaddock Teeg',
 'Gahiji, Honored One',
 'Galadriel of Lothlórien',
 'Galadriel, Elven-Queen',
 'Galadriel, Light of Valinor',
 'Galazeth Prismari',
 'Gale, Waterdeep Prodigy + Scion of Halaster',
 'Galea, Kindler of Hope',
 'Gallia of the Endless Dance',
 'Ganax, Astral Hunter + Acolyte of Bahamut',
 'Ganax, Astral Hunter + Feywild Visitor',
 'Gandalf of the Secret Fire',
 'Gandalf the Grey',
 'Gandalf the White',
 'Gandalf, Westward Voyager',
 'Gargos, Vicious Watcher',
 'Garna, Bloodfist of Keld',
 'Garnet, Princess of Alexandria',
 'Garth One-Eye',
 'Gavi, Nest Warden',
 'Geist of Saint Traft',
 'General Ferrous Rokiric',
 'General Kreat, the Boltbringer',
 'General Kudro of Drannith',
 'General Marhault Elsdragon',
 'General Tazri',
 'Genku, Future Shaper',
 'Geralf, Visionary Stitcher',
 'Geralf, the Fleshwright',
 'Gev, Scaled Scorch',
 'Ghalta and Mavren',
 'Ghalta, Primal Hunger',
 'Ghalta, Stampede Tyrant',
 'Ghave, Guru of Spores',
 'Ghen, Arcanum Weaver',
 'Ghired, Conclave Exile',
 'Ghired, Mirror of the Wilds',
 'Ghoulcaller Gisa',
 'Ghyrson Starn, Kelermorph',
 'Giada, Font of Hope',
 'Gilanra, Caller of Wirewood + Kodama of the East Tree',
 'Gilanra, Caller of Wirewood + Vial Smasher the Fierce',
 'Gilgamesh, Master-at-Arms',
 'Gimbal, Gremlin Prodigy',
 'Gimli, Mournful Avenger',
 'Gisa and Geralf',
 'Gisa, Glorious Resurrector',
 'Gisa, the Hellraiser',
 'Gisela, Blade of Goldnight',
 'Gisela, the Broken Blade',
 "Gishath, Sun's Avatar",
 'Gix, Yawgmoth Praetor',
 "Glarb, Calamity's Augur",
 'Glissa Sunslayer',
 'Glissa, Herald of Predation',
 'Glissa, the Traitor',
 'Gluntch, the Bestower',
 "Go-Shintai of Life's Origin",
 'God-Eternal Oketra',
 'Godo, Bandit Warlord',
 'Gogo, Master of Mimicry',
 'Gogo, Mysterious Mime',
 'Golbez, Crystal Collector',
 "Goldbug, Humanity's Ally",
 'Gollum, Obsessed Stalker',
 'Gonti, Canny Acquisitor',
 'Gonti, Lord of Luxury',
 'Gonti, Night Minister',
 'Gor Muldrak, Amphinologist',
 'Goreclaw, Terror of Qal Sisma',
 'Gorion, Wise Mentor',
 'Gorm the Great + Virtus the Veiled',
 'Gornog, the Red Reaper',
 'Goro-Goro and Satoru',
 'Graaz, Unstoppable Juggernaut',
 'Grand Arbiter Augustin IV',
 'Grand Warlord Radha',
 'Grazilaxx, Illithid Scholar',
 'Greasefang, Okiba Boss',
 'Greensleeves, Maro-Sorcerer',
 'Gregor, Shrewd Magistrate',
 'Grenzo, Dungeon Warden',
 'Grenzo, Havoc Raiser',
 'Greta, Sweettooth Scourge',
 'Gretchen Titchwillow',
 'Greven, Predator Captain',
 "Greymond, Avacyn's Stalwart",
 'Grimgrin, Corpse-Born',
 'Grismold, the Dreadsower',
 'Grist, Voracious Larva',
 'Grist, the Hunger Tide',
 'Grolnok, the Omnivore',
 'Grothama, All-Devouring',
 'Grub, Storied Matriarch',
 'Grumgully, the Generous',
 'Grunn, the Lonely King',
 "Gríma, Saruman's Footman",
 'Gut, True Soul Zealot + Agent of the Iron Throne',
 'Gut, True Soul Zealot + Haunted One',
 'Gut, True Soul Zealot + Inspiring Leader',
 'Gwen Stacy',
 'Gwenna, Eyes of Gaea',
 'Gwenom, Remorseless',
 'Gylwain, Casting Director',
 'Gyome, Master Chef',
 'Gyruda, Doom of Depths',
 'Gyrus, Waker of Corpses',
 'Hakbal of the Surging Soul',
 'Haktos the Unscarred',
 'Halana and Alena, Partners',
 'Haldan, Avid Arcanist + Pako, Arcane Retriever',
 'Haliya, Guided by Light',
 'Hallar, the Firefletcher',
 'Hama Pashar, Ruin Seeker',
 'Hamza, Guardian of Arashin',
 'Hans Eriksson',
 'Hansk, Slayer Zealot',
 'Hapatra, Vizier of Poisons',
 'Harbin, Vanguard Aviator',
 "Hargilde, Kindly Runechanter + Wernog, Rider's Chaplain",
 "Hashaton, Scarab's Fist",
 'Havi, the All-Father',
 'Hazel of the Rootbloom',
 'Hazezon Tamar',
 'Hazezon, Shaper of Sand',
 'Hazoret the Fervent',
 'Hearthhull, the Worldseed',
 'Heartless Hidetsugu',
 'Hei Bai, Forest Guardian',
 'Helga, Skittish Seer',
 'Heliod, Sun-Crowned',
 'Heliod, the Radiant Dawn',
 'Henry Wu, InGen Geneticist',
 'Henzie "Toolbox" Torre',
 'Herigast, Erupting Nullkite',
 'Hermes, Overseer of Elpis',
 'Hidetsugu and Kairi',
 'Hidetsugu, Devouring Chaos',
 'High Perfect Morcant',
 'Hinata, Dawn-Crowned',
 'Hofri Ghostforge',
 'Hogaak, Arisen Necropolis',
 'Hokori, Dust Drinker',
 'Honest Rutstein',
 'Hope Estheim',
 'Horde of Notions',
 "Horobi, Death's Wail",
 'Huatli, Poet of Unity',
 'Hugs, Grisly Guardian',
 'Hylda of the Icy Crown',
 'Ian Malcolm, Chaotician',
 'Ib Halfheart, Goblin Tactician',
 'Ikra Shidiqi, the Usurper + Ishai, Ojutai Dragonspeaker',
 'Ikra Shidiqi, the Usurper + Prava of the Steel Legion',
 'Ikra Shidiqi, the Usurper + Sidar Kondo of Jamuraa',
 'Ikra Shidiqi, the Usurper + Tymna the Weaver',
 'Ilharg, the Raze-Boar',
 'Illuminor Szeras',
 'Illuna, Apex of Wishes',
 'Immard, the Stormcleaver',
 'Imodane, the Pyrohammer',
 'Imotekh the Stormlord',
 'Imoti, Celebrant of Bounty',
 'Imskir Iron-Eater',
 'Inalla, Archmage Ritualist',
 'Iname, Death Aspect',
 'Indominus Rex, Alpha',
 'Indoraptor, the Perfect Hybrid',
 'Inferno of the Star Mounts',
 'Infinite Guideline Station',
 'Inga and Esika',
 'Inniaz, the Gale Force',
 'Inquisitor Eisenhorn',
 'Inquisitor Greyfax',
 'Inspirit, Flagship Vessel',
 'Intet, the Dreamer',
 'Inti, Seneschal of the Sun',
 'Iroas, God of Victory',
 'Iroh, Grand Lotus',
 'Iroh, Tea Master',
 'Iron Man, Titan of Innovation',
 'Iron Spider, Stark Upgrade',
 'Ishai, Ojutai Dragonspeaker + Jeska, Thrice Reborn',
 'Ishai, Ojutai Dragonspeaker + Kediss, Emberclaw Familiar',
 'Ishai, Ojutai Dragonspeaker + Reyhan, Last of the Abzan',
 'Ishkanah, Grafwidow',
 'Isperia, Supreme Judge',
 'Isshin, Two Heavens as One',
 'Isu the Abominable',
 'Ivy, Gleeful Spellthief',
 'Ixhel, Scion of Atraxa',
 'Izoni, Center of the Web',
 'Izoni, Thousand-Eyed',
 "Jace, Vryn's Prodigy",
 'Jackal, Genius Geneticist',
 'Jacob Hauken, Inspector',
 'Jadar, Ghoulcaller of Nephalia',
 'Jadzi, Oracle of Arcavios',
 'Jaheira, Friend of the Forest + Inspiring Leader',
 'Jaheira, Friend of the Forest + Street Urchin',
 'Jalira, Master Polymorphist',
 'Jan Jansen, Chaos Crafter',
 'Jarad, Golgari Lich Lord',
 'Jared Carthalion',
 'Jared Carthalion, True Heir',
 'Jasmine Boreal of the Seven',
 'Jaws, Relentless Predator',
 'Jaxis, the Troublemaker',
 'Jedit Ojanen, Mercenary',
 'Jegantha, the Wellspring',
 "Jeleva, Nephalia's Scourge",
 'Jenara, Asura of War',
 'Jenny Flint + Madame Vastra',
 'Jenova, Ancient Calamity',
 'Jenson Carthalion, Druid Exile',
 'Jerren, Corrupted Bishop',
 'Jeska, Thrice Reborn + Tymna the Weaver',
 'Jeska, Thrice Reborn + Yoshimaru, Ever Faithful',
 'Jetmir, Nexus of Revels',
 'Jhoira of the Ghitu',
 'Jhoira, Ageless Innovator',
 'Jhoira, Weatherlight Captain',
 'Jin Sakai, Ghost of Tsushima',
 'Jin-Gitaxias',
 'Jin-Gitaxias, Progress Tyrant',
 "Jinnie Fay, Jetmir's Second",
 'Jirina Kudro',
 'Jodah, Archmage Eternal',
 'Jodah, the Unifier',
 'Jolene, the Plunder Queen',
 'Jolrael, Voice of Zhalfir',
 'Jon Irenicus, Shattered One',
 'Jor Kadeen, First Goldwarden',
 'Jori En, Ruin Diver',

In [11]:
df_select = df.query("commanders in @keep_commanders")

df_summary = df_select.groupby(["commanders", "commander", "commander2", "released_at", "color", "earliest_sets", "time_since_release"], dropna = False).agg({
    'num_updates': ['mean'],
    'user_id': 'count'
}).reset_index()

df_summary.columns = ['commanders', 'commander', 'commander2', 'released_at', 'color', 'earliest_sets', 'time_since_release', 'average_num_updates', 'num_users']
df_summary

,commanders,commander,commander2,released_at,color,earliest_sets,time_since_release,average_num_updates,num_users
0,"Aang, at the Crossroads","Aang, at the Crossroads",NaN,2025-11-21,GUW,"(tla,)",159,3.291667,792
1,"Aatchik, Emerald Radian","Aatchik, Emerald Radian",NaN,2025-02-14,BG,"(dft,)",439,3.223819,487
2,Abaddon the Despoiler,Abaddon the Despoiler,NaN,2022-10-07,BRU,"(40k,)",730,2.567592,2197
3,"Abdel Adrian, Gorion's Ward + Candlekeep Sage","Abdel Adrian, Gorion's Ward",Candlekeep Sage,2022-06-10,UW,"(clb, clb)",730,3.223785,1564
4,"Abdel Adrian, Gorion's Ward + Far Traveler","Abdel Adrian, Gorion's Ward",Far Traveler,2022-06-10,W,"(clb, clb)",730,3.054118,425
...,...,...,...,...,...,...,...,...,...
1714,Zurgo Stormrender,Zurgo Stormrender,NaN,2025-04-11,BRW,"(tdc,)",383,4.844936,5746
1715,Zurgo and Ojutai,Zurgo and Ojutai,NaN,2023-04-21,RUW,"(mom,)",730,3.238671,662
1716,"Zurgo, Thunder's Decree","Zurgo, Thunder's Decree",NaN,2025-04-11,BRW,"(tdm,)",383,3.739242,1557
1717,"Zurzoth, Chaos Rider","Zurzoth, Chaos Rider",NaN,2020-07-17,R,"(jmp,)",730,2.953264,1348
1718,"Éowyn, Shieldmaiden","Éowyn, Shieldmaiden",NaN,2023-06-23,RUW,"(ltc,)",730,3.335461,5640

In [12]:
# set to parent set name
set_to_parent_set = pd.read_csv("/Users/juliamaddalena/edhrec/edhrec-notebooks/wotc_presentation_analyses/set_to_parent_map.csv")

df_summary_with_sets = df_summary.explode(column = "earliest_sets")\
    .merge(set_to_parent_set, left_on='earliest_sets', right_on='code', how='left')\
    .groupby(["commanders", "commander", "commander2", "released_at", "time_since_release", "color"], dropna = False)\
        .agg({'average_num_updates': 'first', 'num_users': 'first', 
              'parent_set': lambda x: list(x.unique())})\
        .reset_index()

df_summary_with_sets

,commanders,commander,commander2,released_at,time_since_release,color,average_num_updates,num_users,parent_set
0,"Aang, at the Crossroads","Aang, at the Crossroads",NaN,2025-11-21,159,GUW,3.291667,792,[Avatar: The Last Airbender]
1,"Aatchik, Emerald Radian","Aatchik, Emerald Radian",NaN,2025-02-14,439,BG,3.223819,487,[Aetherdrift]
2,Abaddon the Despoiler,Abaddon the Despoiler,NaN,2022-10-07,730,BRU,2.567592,2197,"[Warhammer 40,000 Commander]"
3,"Abdel Adrian, Gorion's Ward + Candlekeep Sage","Abdel Adrian, Gorion's Ward",Candlekeep Sage,2022-06-10,730,UW,3.223785,1564,[Commander Legends: Battle for Baldur's Gate]
4,"Abdel Adrian, Gorion's Ward + Far Traveler","Abdel Adrian, Gorion's Ward",Far Traveler,2022-06-10,730,W,3.054118,425,[Commander Legends: Battle for Baldur's Gate]
...,...,...,...,...,...,...,...,...,...
1714,Zurgo Stormrender,Zurgo Stormrender,NaN,2025-04-11,383,BRW,4.844936,5746,[Tarkir: Dragonstorm]
1715,Zurgo and Ojutai,Zurgo and Ojutai,NaN,2023-04-21,730,RUW,3.238671,662,[March of the Machine]
1716,"Zurgo, Thunder's Decree","Zurgo, Thunder's Decree",NaN,2025-04-11,383,BRW,3.739242,1557,[Tarkir: Dragonstorm]
1717,"Zurzoth, Chaos Rider","Zurzoth, Chaos Rider",NaN,2020-07-17,730,R,2.953264,1348,[Jumpstart]
1718,"Éowyn, Shieldmaiden","Éowyn, Shieldmaiden",NaN,2023-06-23,730,RUW,3.335461,5640,[The Lord of the Rings: Tales of Middle-earth]

In [16]:
df_summary_with_sets.to_parquet("depth_vs_breadth_plot_df.parquet", index=False)

In [15]:
df_summary_with_sets

,commanders,commander,commander2,released_at,time_since_release,color,average_num_updates,num_users,parent_set
0,"Aang, at the Crossroads","Aang, at the Crossroads",NaN,2025-11-21,159,GUW,3.291667,792,[Avatar: The Last Airbender]
1,"Aatchik, Emerald Radian","Aatchik, Emerald Radian",NaN,2025-02-14,439,BG,3.223819,487,[Aetherdrift]
2,Abaddon the Despoiler,Abaddon the Despoiler,NaN,2022-10-07,730,BRU,2.567592,2197,"[Warhammer 40,000 Commander]"
3,"Abdel Adrian, Gorion's Ward + Candlekeep Sage","Abdel Adrian, Gorion's Ward",Candlekeep Sage,2022-06-10,730,UW,3.223785,1564,[Commander Legends: Battle for Baldur's Gate]
4,"Abdel Adrian, Gorion's Ward + Far Traveler","Abdel Adrian, Gorion's Ward",Far Traveler,2022-06-10,730,W,3.054118,425,[Commander Legends: Battle for Baldur's Gate]
...,...,...,...,...,...,...,...,...,...
1714,Zurgo Stormrender,Zurgo Stormrender,NaN,2025-04-11,383,BRW,4.844936,5746,[Tarkir: Dragonstorm]
1715,Zurgo and Ojutai,Zurgo and Ojutai,NaN,2023-04-21,730,RUW,3.238671,662,[March of the Machine]
1716,"Zurgo, Thunder's Decree","Zurgo, Thunder's Decree",NaN,2025-04-11,383,BRW,3.739242,1557,[Tarkir: Dragonstorm]
1717,"Zurzoth, Chaos Rider","Zurzoth, Chaos Rider",NaN,2020-07-17,730,R,2.953264,1348,[Jumpstart]
1718,"Éowyn, Shieldmaiden","Éowyn, Shieldmaiden",NaN,2023-06-23,730,RUW,3.335461,5640,[The Lord of the Rings: Tales of Middle-earth]

In [8]:
fig = px.scatter(
    df_summary_with_sets,
    x="num_users",
    y="average_num_updates",
    color="time_since_release",
    color_continuous_scale=px.colors.sequential.thermal[::-1],
    hover_name="commanders",
    hover_data={
        "num_users": ":,.0f",
        "average_num_updates": ":.3f",
        "commanders": False,
    },
    labels={
        "num_users": "# users with a deck for this commander",
        "average_num_updates": "average # deck updates for this commander across users",
        "time_since_release": "days since commander release  (2 year cap)",
    },
    title="Breadth (x) vs Depth (y) for commanders in the last two years",
    log_x=True,
    width=1200,
    height=800,
    render_mode="svg",
)

fig.write_html("breadth_vs_depth_updates_after_60_day_burn_in.html")
fig.show()